//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoFrame.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Photo
    {
        public string Id { get; set; }
        public string FilePath { get; set; }
        public Nullable<bool> IsFavorite { get; set; }
        public string AlbumId { get; set; }
    
        public virtual M_Album M_Album { get; set; }
    }
}
